import type { Song } from "./types"

export const SongDatabase: Song[] = [
  {
    id: "song1",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    year: 1975,
    genre: "Rock",
    albumCover: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "song2",
    title: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    year: 1982,
    genre: "Pop",
    albumCover: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "song3",
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    year: 2017,
    genre: "Pop",
    albumCover: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "song4",
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
    year: 1971,
    genre: "Rock",
    albumCover: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "song5",
    title: "Imagine",
    artist: "John Lennon",
    album: "Imagine",
    year: 1971,
    genre: "Rock",
    albumCover: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "song6",
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    album: "Appetite for Destruction",
    year: 1987,
    genre: "Rock",
    albumCover: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "song7",
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    album: "Nevermind",
    year: 1991,
    genre: "Grunge",
    albumCover: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "song8",
    title: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
    year: 1976,
    genre: "Rock",
    albumCover: "/placeholder.svg?height=200&width=200",
  },
]
